name: Run tests and linters on push event

on: 
  push:
    tags:
      - '!refs/tags/*'
    branches:
      - '*'

jobs:
  run-tests:
    runs-on: [golang:1.23]
    steps:
      - name: Donload libs
        run: go mod download
      - name: start test
        run: go test ./...
